from .account import CustomUserAdmin
from .brand import BrandAdmin, SchoolAdmin
from .academic import (
    YearAdmin,
    TermAdmin,
    SubjectAdmin,
    ClassroomAdmin,
    ActiveYearAdmin,
    ActiveSubjectAdmin,
    ActiveClassroomAdmin,
    ActiveStudentAdmin,
)
from .learning import (
    MaterialAdmin,
    AssignmentAdmin,
    AssignmentSubmissionAdmin,
    QuestionBankAdmin,
    QuestionAdmin,
    AnswerOptionAdmin,
    QuizAdmin,
    QuizAttemptAdmin,
    ExamAdmin,
    ExamAttemptAdmin,
    GradeAdmin,
    ReportCardAdmin,
)

__all__ = [
    "CustomUserAdmin",
    "BrandAdmin",
    "SchoolAdmin",
    "YearAdmin",
    "TermAdmin",
    "SubjectAdmin",
    "ClassroomAdmin",
    "ActiveYearAdmin",
    "ActiveSubjectAdmin",
    "ActiveClassroomAdmin",
    "ActiveStudentAdmin",
    "MaterialAdmin",
    "AssignmentAdmin",
    "AssignmentSubmissionAdmin",
    "QuestionBankAdmin",
    "QuestionAdmin",
    "AnswerOptionAdmin",
    "QuizAdmin",
    "QuizAttemptAdmin",
    "ExamAdmin",
    "ExamAttemptAdmin",
    "GradeAdmin",
    "ReportCardAdmin",
]
